### ISSUE TITLE
ip hasn't changed

### ISSUE THREAD

**Issue by spartacruz** [kboghe/NordVPN-switcher#24] opened 2021-05-05 09:56 UTC
Hi There,

I just used your script, and made it rotate on asia pasific server every hour.

The issue is : the script keeps saying "my ip address hasn't changed."
The truth is : my ip already changed because my pc is successfully connected to another server. I saw it live through the NordVPN application.

Then, script will always try to reconnect to another server (even though it is already connected to x server) and bypass my rule (to be changed every hour).

Screenshot attached. 
![Capturqqe](https://user-images.githubusercontent.com/18097823/117124201-3a66ac00-adc2-11eb-8c00-6ec6b542e536.JPG)

Could you please assist me with this? why it wrongly detected? 
or Could I bypass ip address checking?

Some detail information:
-Not using kill switch
-Use split tunneling - for chrome only

-Windows server 2016 64bit
-Intel Xeon Platinum 8175M
-an remote pc instance from Amazon Workspaces client.

Thank you.

Regards,
-Yuri

**Comment by kauttoj** [comment] 2021-10-06 19:35
I have also this problem. Also getting lots of "CERTIFICATE_VERIFY_FAILED" errors lately. Maybe related?

**Comment by luisjvca-menhir** [comment] 2021-12-16 13:05
same here ;(

**Comment by kboghe** [comment] 2021-12-21 18:18
> having that same problem... there's no concern on solving our issue, apparently...

Hi there,

Do you realize this is a *free* package that I've written and still maintaining in my *spare time*? You could also alter the code any way you like if you have a solution. 

I'm truly sorry that the package doesn't work as intended for some people, but it works for me and plenty of other users. I compiled a list of potential fixes, and I'm sure I'll come around to it somewhere in the coming months. Perhaps one of these fixes would solve this issue as well. 

I have no issue with people emailing me (and they do), asking questions on how to use the package or how they could implement a particular use case. Not at all. But I don't need snarky comments like this one; as if I owe you something.

Best,
Kristof

**Comment by spartacruz** [comment] 2021-12-22 00:57
> > having that same problem... there's no concern on solving our issue, apparently...
> 
> Hi there,
> 
> Do you realize this is a _free_ package that I've written and still maintaining in my _spare time_? You could also alter the code any way you like if you have a solution.
> 
> I'm truly sorry that the package doesn't work as intended for some people, but it works for me and plenty of other users. I compiled a list of potential fixes, and I'm sure I'll come around to it somewhere in the coming months. Perhaps one of these fixes would solve this issue as well.
> 
> I have no issue with people emailing me (and they do), asking questions on how to use the package or how they could implement a particular use case. Not at all. But I don't need snarky comments like this one; as if I owe you something.
> 
> Best, Kristof

Hi Kristof,
@kboghe 

Although this is a old issue, thank you for jumping in & huge thank you for keep maintain this free package in your spare time.
Chill dude, often text communication lead to misunderstanding due to limited expression rather than face2face.

I am not taking any side, but sometimes (as you may know also) users of Github script are not an experienced engineer and had difficulties to modify / alter it directly.

For me, I already had to modify your code (locally) to temporary fix this issue.

Looking forward for the potential fixes..

Regards,
-Yuri

**Comment by kboghe** [comment] 2021-12-22 06:41
> > > having that same problem... there's no concern on solving our issue, apparently...
> > 
> > 
> > Hi there,
> > Do you realize this is a _free_ package that I've written and still maintaining in my _spare time_? You could also alter the code any way you like if you have a solution.
> > I'm truly sorry that the package doesn't work as intended for some people, but it works for me and plenty of other users. I compiled a list of potential fixes, and I'm sure I'll come around to it somewhere in the coming months. Perhaps one of these fixes would solve this issue as well.
> > I have no issue with people emailing me (and they do), asking questions on how to use the package or how they could implement a particular use case. Not at all. But I don't need snarky comments like this one; as if I owe you something.
> > Best, Kristof
> 
> Hi Kristof, @kboghe
> 
> Although this is a old issue, thank you for jumping in & huge thank you for keep maintain this free package in your spare time. Chill dude, often text communication lead to misunderstanding due to limited expression rather than face2face.
> 
> I am not taking any side, but sometimes (as you may know also) users of Github script are not an experienced engineer and had difficulties to modify / alter it directly.
> 
> For me, I already had to modify your code (locally) to temporary fix this issue.
> 
> Looking forward for the potential fixes..
> 
> Regards, -Yuri

Hi Yuri,

Sure, not everyone can modify the code, but I'm kind of taking issue with this customer service attitude on Github towards people who are just sharing their code. To be clear, no hard feelings towards @dangstan or anything at al, I'm just stating my point of view. 

Maybe I've missed it somewhere, but could you share your fix for this issue? That would be great! 

Best,
Kristof

**Closed** 2022-06-25 07:05 UTC
