### ISSUE TITLE
Can't Get to Work

### ISSUE THREAD

**Issue by baD714** [kboghe/NordVPN-switcher#5] opened 2021-01-08 20:41 UTC
Hey im trying to run this on ubuntu and it simply wont work. Installed Nord and it works fine but can't use your script to rotate. Help please thanks

**Comment by baD714** [comment] 2021-01-08 20:41
I get an error saying
![image](https://user-images.githubusercontent.com/37461503/104062203-05f23300-51c8-11eb-9e14-3633062d9d77.png)

**Comment by kboghe** [comment] 2021-01-08 22:01
Hi, thanks for using my package! Everything seems to work fine on my Ubuntu machine (I double-checked it just moments ago). Have you tried running the following command? 

sudo pip install --upgrade psutil

If this doesn't work, maybe take a look at the following suggestion at Stackoverflow: https://stackoverflow.com/questions/50132740/importerror-no-module-named-psutil

**Comment by baD714** [comment] 2021-01-09 02:02
pip doesn't work on my machine so I use pip3. Is there a difference? What command do you run to start it up, maybe I'm doing the wrong thing

**Comment by baD714** [comment] 2021-01-09 04:32
Alright I got it to work but now im attempting to initialise it and it wont create me a settings file. Any ideas?

**Comment by baD714** [comment] 2021-01-09 04:32
I'm doing this part 
![image](https://user-images.githubusercontent.com/37461503/104083103-ce0bdf80-5209-11eb-97c5-0397b556b1d0.png)

**Comment by kboghe** [comment] 2021-01-09 13:19
I'm afraid it's next to impossible to diagnose the issue without posting your code. 
Anyway, there are multiple ways of leveraging the initialize function. You can save the settings in the Python environment itself without actually creating a settings file. 

from nordvpn_switcher import initialize_VPN,rotate_VPN,terminate_VPN
For example, here you initialize and save the settings to a 'settings' variable: 

settings = initialize_VPN() 
rotate_VPN(settings) 
rotate_VPN(settings,google_check=1) 
terminate_VPN(settings)

If you'd like to save the settings to your hard drive, try the following piece of code: 

#do this once
initialize_VPN(save=1)

#open project on a later date and just use the following two lines of code:
rotate_VPN()
#do stuff
terminate_VPN()

**Comment by kboghe** [comment] 2021-01-10 15:55
I'm going to close this issue, since it seems that the package is working as intended. If you're having any further questions, please contact me on kboghe@gmail.com. Thanks again for using nordvpn switcher!

**Closed by kboghe** 2021-01-10 15:55 UTC
