### ISSUE TITLE
issue installing

### ISSUE THREAD

**Issue by monpseudoestpris** [kboghe/NordVPN-switcher#7] opened 2021-01-14 14:17 UTC
Hello,

I already installed nordvpn-switcher with success on several computers, but trying today gave that:
ERROR: Could not find a version that satisfies the requirement urllib (from versions: none)
ERROR: No matching distribution found for urllib
So I can not install !

Regards,

**Comment by kboghe** [comment] 2021-01-14 20:51
Hi, 

I'll try to fix this by deleting the urllib requirement (since it's already part of the standard library) and updating the project. One important question, though: do you use Python 3.7 (or even a more recent version)?

**Comment by kboghe** [comment] 2021-01-14 21:20
OK, instead of updating the code to urllib3, I tried to specify the import of urllib by module (so instead of importing urllib, the script imports specific parts of the folder); I've read on Stackoverflow this might cause some issues in a couple of environments (such as Spyder). 

I just uploaded a new version (0.1.9) --> https://pypi.org/project/nordvpn-switcher/ 
Go ahead and try to install it using pip, and please let me know whether this has solved the issue!

**Comment by diCagri** [comment] 2021-01-15 07:36
Hi, 

I am getting same issue. I think you need to remove urllib in the requeriemnts because urllib is a python3 stardart library so you dont need to pip install it because you cant find it. It comes when you installing python so thats is gives the issue. Can you try it?

**Comment by kboghe** [comment] 2021-01-15 10:42
Hmm, seems that urllib does seem to pop up automatically as a requirement when I'm creating the wheel file.  I'll fix this in a couple of hours (after work). Thanks for the suggestion!

**Comment by kboghe** [comment] 2021-01-15 16:42
Alright, the issue should be fixed by now. Try and install the latest version and let me know whether this has solved the issue.

**Comment by kboghe** [comment] 2021-01-18 15:09
I'll assume the issue is fixed then! 
Thanks for bringing this issue to my attention. :)

**Closed by kboghe** 2021-01-18 15:09 UTC
Labels: bug
